name: LambdaTonic
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "22"
      - name: Install Maven
        run: |
          sudo apt update -y
          sudo apt install -y maven
      - name: Run unit tests
        run: mvn test
